server:
  port: 15000

spring:
  application:
    name: motion-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@motion-mongodb-service:27017/motionDB?authSource=motionDB
      auto-index-creation: true
      uuid-representation: standard