server:
  port: 15000

spring:
  application:
    name: motion-service
  data:
    mongodb:
      uri: mongodb://poly:poly1234@motion-mongodb:27017/motionDB?authSource=motionDB
      auto-index-creation: true
      uuid-representation: standard