# =========================================
# Motion-Service (prod) - Spring Cloud Config
# 목적: 운영 환경용. 민감 정보는 K8s Secret으로 주입, 성능 최적화 설정.
# =========================================
server:
  port: 15000
  shutdown: graceful # 운영 환경에서는 요청을 모두 처리하고 안전하게 종료하는 것이 중요합니다.

spring:
  application:
    name: motion-service
  config:
    activate:
      on-profile: prod # 이 파일은 prod 프로필에서만 활성화됩니다.
  data:
    mongodb:
      # K8s 내부 DNS 이름을 사용합니다. (예: 'motion-mongodb-prod.datastore.svc.cluster.local')
      # 사용자 이름과 비밀번호는 K8s Secret을 통해 환경변수(MONGO_USER, MONGO_PASSWORD)로 주입받습니다.
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@motion-mongodb-prod:27017/motionDBProd?authSource=admin
      auto-index-creation: false # 운영에서는 성능을 위해 인덱스를 수동으로 관리하는 것을 권장합니다.
      uuid-representation: standard

# 운영 환경 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    kopo.motionservice: INFO

# Actuator 보안 설정: 운영에서는 최소한의 엔드포인트만 노출합니다.
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # 헬스체크, 기본정보, 모니터링 메트릭만 노출
  endpoint:
    health:
      show-details: when-authorized